//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 5/25/2011 10:31:34 AM
namespace Pinsonault.Application.UnitedThera
{
    
    /// <summary>
    /// There are no comments for PathfinderUnitedTheraEntities in the schema.
    /// </summary>
    public partial class PathfinderUnitedTheraEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new PathfinderUnitedTheraEntities object using the connection string found in the 'PathfinderUnitedTheraEntities' section of the application configuration file.
        /// </summary>
        public PathfinderUnitedTheraEntities() : 
                base("name=PathfinderUnitedTheraEntities", "PathfinderUnitedTheraEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new PathfinderUnitedTheraEntities object.
        /// </summary>
        public PathfinderUnitedTheraEntities(string connectionString) : 
                base(connectionString, "PathfinderUnitedTheraEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new PathfinderUnitedTheraEntities object.
        /// </summary>
        public PathfinderUnitedTheraEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "PathfinderUnitedTheraEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
    }
}
