//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3634
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("PPRXModel", "FK_Lkp_PP_Brand_Lkp_PP_Market_Basket_MB_ID", "Lkp_PP_Market_Basket", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Pinsonault.Application.PowerPlanRx.PPMarketBasket), "Lkp_PP_Brand", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Pinsonault.Application.PowerPlanRx.PPBrand))]

// Original file name:
// Generation date: 10/22/2012 2:22:16 PM
namespace Pinsonault.Application.PowerPlanRx
{
    
    /// <summary>
    /// There are no comments for PPRXEntities in the schema.
    /// </summary>
    public partial class PPRXEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new PPRXEntities object using the connection string found in the 'PPRXEntities' section of the application configuration file.
        /// </summary>
        public PPRXEntities() : 
                base("name=PPRXEntities", "PPRXEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new PPRXEntities object.
        /// </summary>
        public PPRXEntities(string connectionString) : 
                base(connectionString, "PPRXEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new PPRXEntities object.
        /// </summary>
        public PPRXEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "PPRXEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for PPBrandSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<PPBrand> PPBrandSet
        {
            get
            {
                if ((this._PPBrandSet == null))
                {
                    this._PPBrandSet = base.CreateQuery<PPBrand>("[PPBrandSet]");
                }
                return this._PPBrandSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<PPBrand> _PPBrandSet;
        /// <summary>
        /// There are no comments for PPMarketBasketSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<PPMarketBasket> PPMarketBasketSet
        {
            get
            {
                if ((this._PPMarketBasketSet == null))
                {
                    this._PPMarketBasketSet = base.CreateQuery<PPMarketBasket>("[PPMarketBasketSet]");
                }
                return this._PPMarketBasketSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<PPMarketBasket> _PPMarketBasketSet;
        /// <summary>
        /// There are no comments for PPBrandSet in the schema.
        /// </summary>
        public void AddToPPBrandSet(PPBrand pPBrand)
        {
            base.AddObject("PPBrandSet", pPBrand);
        }
        /// <summary>
        /// There are no comments for PPMarketBasketSet in the schema.
        /// </summary>
        public void AddToPPMarketBasketSet(PPMarketBasket pPMarketBasket)
        {
            base.AddObject("PPMarketBasketSet", pPMarketBasket);
        }
    }
    /// <summary>
    /// There are no comments for PPRXModel.PPBrand in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PP_Brand_ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="PPRXModel", Name="PPBrand")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class PPBrand : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new PPBrand object.
        /// </summary>
        /// <param name="pP_Brand_ID">Initial value of PP_Brand_ID.</param>
        public static PPBrand CreatePPBrand(int pP_Brand_ID)
        {
            PPBrand pPBrand = new PPBrand();
            pPBrand.PP_Brand_ID = pP_Brand_ID;
            return pPBrand;
        }
        /// <summary>
        /// There are no comments for Property PP_Brand_ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int PP_Brand_ID
        {
            get
            {
                return this._PP_Brand_ID;
            }
            set
            {
                this.OnPP_Brand_IDChanging(value);
                this.ReportPropertyChanging("PP_Brand_ID");
                this._PP_Brand_ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("PP_Brand_ID");
                this.OnPP_Brand_IDChanged();
            }
        }
        private int _PP_Brand_ID;
        partial void OnPP_Brand_IDChanging(int value);
        partial void OnPP_Brand_IDChanged();
        /// <summary>
        /// There are no comments for Property PP_Brand_Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PP_Brand_Name
        {
            get
            {
                return this._PP_Brand_Name;
            }
            set
            {
                this.OnPP_Brand_NameChanging(value);
                this.ReportPropertyChanging("PP_Brand_Name");
                this._PP_Brand_Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("PP_Brand_Name");
                this.OnPP_Brand_NameChanged();
            }
        }
        private string _PP_Brand_Name;
        partial void OnPP_Brand_NameChanging(string value);
        partial void OnPP_Brand_NameChanged();
        /// <summary>
        /// There are no comments for Property Is_Campaign_Brand in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> Is_Campaign_Brand
        {
            get
            {
                return this._Is_Campaign_Brand;
            }
            set
            {
                this.OnIs_Campaign_BrandChanging(value);
                this.ReportPropertyChanging("Is_Campaign_Brand");
                this._Is_Campaign_Brand = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Is_Campaign_Brand");
                this.OnIs_Campaign_BrandChanged();
            }
        }
        private global::System.Nullable<bool> _Is_Campaign_Brand;
        partial void OnIs_Campaign_BrandChanging(global::System.Nullable<bool> value);
        partial void OnIs_Campaign_BrandChanged();
        /// <summary>
        /// There are no comments for Lkp_PP_Market_Basket in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("PPRXModel", "FK_Lkp_PP_Brand_Lkp_PP_Market_Basket_MB_ID", "Lkp_PP_Market_Basket")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public PPMarketBasket Lkp_PP_Market_Basket
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<PPMarketBasket>("PPRXModel.FK_Lkp_PP_Brand_Lkp_PP_Market_Basket_MB_ID", "Lkp_PP_Market_Basket").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<PPMarketBasket>("PPRXModel.FK_Lkp_PP_Brand_Lkp_PP_Market_Basket_MB_ID", "Lkp_PP_Market_Basket").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Lkp_PP_Market_Basket in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<PPMarketBasket> Lkp_PP_Market_BasketReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<PPMarketBasket>("PPRXModel.FK_Lkp_PP_Brand_Lkp_PP_Market_Basket_MB_ID", "Lkp_PP_Market_Basket");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<PPMarketBasket>("PPRXModel.FK_Lkp_PP_Brand_Lkp_PP_Market_Basket_MB_ID", "Lkp_PP_Market_Basket", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for PPRXModel.PPMarketBasket in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PP_MB_ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="PPRXModel", Name="PPMarketBasket")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class PPMarketBasket : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new PPMarketBasket object.
        /// </summary>
        /// <param name="pP_MB_ID">Initial value of PP_MB_ID.</param>
        public static PPMarketBasket CreatePPMarketBasket(int pP_MB_ID)
        {
            PPMarketBasket pPMarketBasket = new PPMarketBasket();
            pPMarketBasket.PP_MB_ID = pP_MB_ID;
            return pPMarketBasket;
        }
        /// <summary>
        /// There are no comments for Property PP_MB_ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int PP_MB_ID
        {
            get
            {
                return this._PP_MB_ID;
            }
            set
            {
                this.OnPP_MB_IDChanging(value);
                this.ReportPropertyChanging("PP_MB_ID");
                this._PP_MB_ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("PP_MB_ID");
                this.OnPP_MB_IDChanged();
            }
        }
        private int _PP_MB_ID;
        partial void OnPP_MB_IDChanging(int value);
        partial void OnPP_MB_IDChanged();
        /// <summary>
        /// There are no comments for Property PP_MB_Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PP_MB_Name
        {
            get
            {
                return this._PP_MB_Name;
            }
            set
            {
                this.OnPP_MB_NameChanging(value);
                this.ReportPropertyChanging("PP_MB_Name");
                this._PP_MB_Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("PP_MB_Name");
                this.OnPP_MB_NameChanged();
            }
        }
        private string _PP_MB_Name;
        partial void OnPP_MB_NameChanging(string value);
        partial void OnPP_MB_NameChanged();
        /// <summary>
        /// There are no comments for Lkp_PP_Brand in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("PPRXModel", "FK_Lkp_PP_Brand_Lkp_PP_Market_Basket_MB_ID", "Lkp_PP_Brand")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<PPBrand> Lkp_PP_Brand
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<PPBrand>("PPRXModel.FK_Lkp_PP_Brand_Lkp_PP_Market_Basket_MB_ID", "Lkp_PP_Brand");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<PPBrand>("PPRXModel.FK_Lkp_PP_Brand_Lkp_PP_Market_Basket_MB_ID", "Lkp_PP_Brand", value);
                }
            }
        }
    }
}
