//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3634
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pinsonault.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pinsonault.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PathfinderRx.
        /// </summary>
        public static string Assembly_ApplicationName {
            get {
                return ResourceManager.GetString("Assembly_ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinsonault Associates, LLC.
        /// </summary>
        public static string Assembly_CompanyName {
            get {
                return ResourceManager.GetString("Assembly_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Favorite.
        /// </summary>
        public static string DialogTitle_AddFavorite {
            get {
                return ResourceManager.GetString("DialogTitle_AddFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Meeting.
        /// </summary>
        public static string DialogTitle_AddMeeting {
            get {
                return ResourceManager.GetString("DialogTitle_AddMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string DialogTitle_ChangePassword {
            get {
                return ResourceManager.GetString("DialogTitle_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Search.
        /// </summary>
        public static string DialogTitle_ContactSearch {
            get {
                return ResourceManager.GetString("DialogTitle_ContactSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Export.
        /// </summary>
        public static string DialogTitle_Export_Confirmation {
            get {
                return ResourceManager.GetString("DialogTitle_Export_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string DialogTitle_Favorites {
            get {
                return ResourceManager.GetString("DialogTitle_Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell Sheet.
        /// </summary>
        public static string DialogTitle_SellSheet {
            get {
                return ResourceManager.GetString("DialogTitle_SellSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      Please remove the existing campaign for the below campaign id-
        ///    .
        /// </summary>
        public static string EMailBody_CampaignCreateRequest {
            get {
                return ResourceManager.GetString("EMailBody_CampaignCreateRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please plan to attend an important planning meeting to develop a pull-through campaign for.
        /// </summary>
        public static string EMailBody_MeetingRequest {
            get {
                return ResourceManager.GetString("EMailBody_MeetingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During the meeting we will use the Impact website to:.
        /// </summary>
        public static string EMailBody_MeetingRequest2 {
            get {
                return ResourceManager.GetString("EMailBody_MeetingRequest2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next steps and team member roles and responsibilities in executing the campaign will also be discussed..
        /// </summary>
        public static string EMailBody_NextSteps {
            get {
                return ResourceManager.GetString("EMailBody_NextSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may review the pull-through Opportunity Assessment for.
        /// </summary>
        public static string EMailBody_Review {
            get {
                return ResourceManager.GetString("EMailBody_Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in advance of the meeting by clicking on this link to the Impact website:.
        /// </summary>
        public static string EMailBody_Review2 {
            get {
                return ResourceManager.GetString("EMailBody_Review2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks and Regards,.
        /// </summary>
        public static string EMailSignature_CampaignCreateRequest {
            get {
                return ResourceManager.GetString("EMailSignature_CampaignCreateRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you in advance for helping to make the campaign a success!.
        /// </summary>
        public static string EMailSignature_MeetingRequest {
            get {
                return ResourceManager.GetString("EMailSignature_MeetingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign Create Request.
        /// </summary>
        public static string EMailSubject_CampaignCreateRequest {
            get {
                return ResourceManager.GetString("EMailSubject_CampaignCreateRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull-Through Campaign Planning Meeting for.
        /// </summary>
        public static string EmailSubject_MeetingRequest {
            get {
                return ResourceManager.GetString("EmailSubject_MeetingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Favorite_Cancel {
            get {
                return ResourceManager.GetString("Favorite_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Favorite.
        /// </summary>
        public static string Favorite_Save {
            get {
                return ResourceManager.GetString("Favorite_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email address and press &apos;Submit&apos; or contact Customer Support at 800.372.9009.&lt;br /&gt;.
        /// </summary>
        public static string ForgotPassword_Instructions {
            get {
                return ResourceManager.GetString("ForgotPassword_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email address and press &apos;Submit&apos; or contact Customer Support at 800.372.9009.&lt;br /&gt;A temporary password will be emailed to you. &lt;br /&gt; Please check your email and follow the instructions to reset your password..
        /// </summary>
        public static string ForgotPassword_Instructions_Auto {
            get {
                return ResourceManager.GetString("ForgotPassword_Instructions_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address you have entered does not match any records in our system..
        /// </summary>
        public static string ForgotPassword_InvalidEmailError {
            get {
                return ResourceManager.GetString("ForgotPassword_InvalidEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} has requested a password change.
        ///
        ///Client: {2}
        ///E-Mail: {3}.
        /// </summary>
        public static string ForgotPassword_MessageFormat {
            get {
                return ResourceManager.GetString("ForgotPassword_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string ForgotPassword_MessageFormat_Auto {
            get {
                return ResourceManager.GetString("ForgotPassword_MessageFormat_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PathfinderRx: Forgot Password Request for {0} {1} of {2}.
        /// </summary>
        public static string ForgotPassword_MessageSubject {
            get {
                return ResourceManager.GetString("ForgotPassword_MessageSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PathfinderRx: Forgot Password Request.
        /// </summary>
        public static string ForgotPassword_MessageSubject_Auto {
            get {
                return ResourceManager.GetString("ForgotPassword_MessageSubject_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we are unable to submit your request at this time.  Please try again later or call customer support..
        /// </summary>
        public static string ForgotPassword_ServerError {
            get {
                return ResourceManager.GetString("ForgotPassword_ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request for a new password has been submitted..
        /// </summary>
        public static string ForgotPassword_Submitted {
            get {
                return ResourceManager.GetString("ForgotPassword_Submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A temporary password has been emailed to you..
        /// </summary>
        public static string ForgotPassword_Submitted_Auto {
            get {
                return ResourceManager.GetString("ForgotPassword_Submitted_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email address..
        /// </summary>
        public static string ForgotPassword_Validation_EmailRequired {
            get {
                return ResourceManager.GetString("ForgotPassword_Validation_EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span UNSELECTABLE=&quot;on&quot; title=&quot;Press Ctrl+Click to follow link&quot; class=&quot;planLink&quot; onmousemove=&quot;this.style.cursor=(event.ctrlKey ? Cursor.Pointer : Cursor.None);&quot; onclick=&quot;return $openPlanWebsite(this, event)&quot;&gt;{0}&amp;nbsp;&lt;/span&gt;.
        /// </summary>
        public static string HTML_PlanWebsite_Link {
            get {
                return ResourceManager.GetString("HTML_PlanWebsite_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Label_About {
            get {
                return ResourceManager.GetString("Label_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Manager.
        /// </summary>
        public static string Label_Account_Manager {
            get {
                return ResourceManager.GetString("Label_Account_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        public static string Label_Account_Name {
            get {
                return ResourceManager.GetString("Label_Account_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Type.
        /// </summary>
        public static string Label_Account_Type {
            get {
                return ResourceManager.GetString("Label_Account_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites:.
        /// </summary>
        public static string Label_Add_To_Favorites {
            get {
                return ResourceManager.GetString("Label_Add_To_Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Current View to Favorites.
        /// </summary>
        public static string Label_Add_To_Favorites_Tooltip {
            get {
                return ResourceManager.GetString("Label_Add_To_Favorites_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Label_Address {
            get {
                return ResourceManager.GetString("Label_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 1.
        /// </summary>
        public static string Label_Address_Line1 {
            get {
                return ResourceManager.GetString("Label_Address_Line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 2.
        /// </summary>
        public static string Label_Address_Line2 {
            get {
                return ResourceManager.GetString("Label_Address_Line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Type.
        /// </summary>
        public static string Label_Address_Type {
            get {
                return ResourceManager.GetString("Label_Address_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affiliation.
        /// </summary>
        public static string Label_Affiliation {
            get {
                return ResourceManager.GetString("Label_Affiliation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Label_All {
            get {
                return ResourceManager.GetString("Label_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Tiers.
        /// </summary>
        public static string Label_All_Tiers {
            get {
                return ResourceManager.GetString("Label_All_Tiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant.
        /// </summary>
        public static string Label_Assistant_Name {
            get {
                return ResourceManager.GetString("Label_Assistant_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Phone.
        /// </summary>
        public static string Label_Assistant_Phone {
            get {
                return ResourceManager.GetString("Label_Assistant_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulary.
        /// </summary>
        public static string Label_BD_FormularyName {
            get {
                return ResourceManager.GetString("Label_BD_FormularyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lives.
        /// </summary>
        public static string Label_BD_Lives {
            get {
                return ResourceManager.GetString("Label_BD_Lives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % of Lives.
        /// </summary>
        public static string Label_BD_PercentLives {
            get {
                return ResourceManager.GetString("Label_BD_PercentLives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an account and then press Continue to add a Customer Contact Report.
        /// </summary>
        public static string Label_CCR_Add_Instructions {
            get {
                return ResourceManager.GetString("Label_CCR_Add_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        public static string Label_Channel {
            get {
                return ResourceManager.GetString("Label_Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data.
        /// </summary>
        public static string Label_Chart_No_Data {
            get {
                return ResourceManager.GetString("Label_Chart_No_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To export drag chart icon into desired application (right click icon for more options).
        /// </summary>
        public static string Label_Chart_Thumbnail_Instruct {
            get {
                return ResourceManager.GetString("Label_Chart_Thumbnail_Instruct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Label_City {
            get {
                return ResourceManager.GetString("Label_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Label_Clear {
            get {
                return ResourceManager.GetString("Label_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial Plan.
        /// </summary>
        public static string Label_Commercial_Plan {
            get {
                return ResourceManager.GetString("Label_Commercial_Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Type.
        /// </summary>
        public static string Label_Contact_Type {
            get {
                return ResourceManager.GetString("Label_Contact_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Lives.
        /// </summary>
        public static string Label_Covered_Lives {
            get {
                return ResourceManager.GetString("Label_Covered_Lives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Covered Lives.
        /// </summary>
        public static string Label_Covered_Lives_Report {
            get {
                return ResourceManager.GetString("Label_Covered_Lives_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Date.
        /// </summary>
        public static string Label_CR_Date {
            get {
                return ResourceManager.GetString("Label_CR_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Support.
        /// </summary>
        public static string Label_Customer_Support {
            get {
                return ResourceManager.GetString("Label_Customer_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Label_Delete {
            get {
                return ResourceManager.GetString("Label_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation.
        /// </summary>
        public static string Label_Designation {
            get {
                return ResourceManager.GetString("Label_Designation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed View.
        /// </summary>
        public static string Label_Detailed_View {
            get {
                return ResourceManager.GetString("Label_Detailed_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type.
        /// </summary>
        public static string Label_Document_Type {
            get {
                return ResourceManager.GetString("Label_Document_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drug Name.
        /// </summary>
        public static string Label_Drug_Name {
            get {
                return ResourceManager.GetString("Label_Drug_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drug Utilization Review.
        /// </summary>
        public static string Label_Drug_Utilization_Review {
            get {
                return ResourceManager.GetString("Label_Drug_Utilization_Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drug Selection.
        /// </summary>
        public static string Label_DrugID {
            get {
                return ResourceManager.GetString("Label_DrugID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string Label_DrugSelection {
            get {
                return ResourceManager.GetString("Label_DrugSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Label_Email {
            get {
                return ResourceManager.GetString("Label_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Label_Fax {
            get {
                return ResourceManager.GetString("Label_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow highlight represents a formulary change.
        /// </summary>
        public static string Label_FHR_Note {
            get {
                return ResourceManager.GetString("Label_FHR_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please browse for a file to be uploaded..
        /// </summary>
        public static string Label_File_Upload_Validator {
            get {
                return ResourceManager.GetString("Label_File_Upload_Validator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string Label_First_Name {
            get {
                return ResourceManager.GetString("Label_First_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All &lt;span style=&apos;font-weight:bold&apos;&gt;{0}&lt;/span&gt; Accounts having &lt;span style=&apos;font-weight:bold&apos;&gt;{1}&lt;/span&gt; with formulary status &lt;span style=&apos;font-weight:bold&apos;&gt;{2}&lt;/span&gt;..
        /// </summary>
        public static string Label_Formulary_Coverage_DrillDown {
            get {
                return ResourceManager.GetString("Label_Formulary_Coverage_DrillDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Covered Without Restriction(s).
        /// </summary>
        public static string Label_Formulary_Status_1 {
            get {
                return ResourceManager.GetString("Label_Formulary_Status_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Covered With Selected Restriction(s).
        /// </summary>
        public static string Label_Formulary_Status_2 {
            get {
                return ResourceManager.GetString("Label_Formulary_Status_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Covered.
        /// </summary>
        public static string Label_Formulary_Status_3 {
            get {
                return ResourceManager.GetString("Label_Formulary_Status_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Covered with Unselected Restriction(s).
        /// </summary>
        public static string Label_Formulary_Status_5 {
            get {
                return ResourceManager.GetString("Label_Formulary_Status_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All &lt;span style=&apos;font-weight:bold&apos;&gt;{0}&lt;/span&gt; Accounts having &lt;span style=&apos;font-weight:bold&apos;&gt;{1}&lt;/span&gt; with formulary status &lt;span style=&apos;font-weight:bold&apos;&gt;{2}&lt;/span&gt;..
        /// </summary>
        public static string Label_Formulary_Status_DrillDown {
            get {
                return ResourceManager.GetString("Label_Formulary_Status_DrillDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulary Type.
        /// </summary>
        public static string Label_FormularyType {
            get {
                return ResourceManager.GetString("Label_FormularyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fortune 500 Rank.
        /// </summary>
        public static string Label_Fortune_500_Rank {
            get {
                return ResourceManager.GetString("Label_Fortune_500_Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geography.
        /// </summary>
        public static string Label_Geography {
            get {
                return ResourceManager.GetString("Label_Geography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Label_Help {
            get {
                return ResourceManager.GetString("Label_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Label_Home {
            get {
                return ResourceManager.GetString("Label_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid date format (xx/xx/xxxx).
        /// </summary>
        public static string Label_Invalid_Date {
            get {
                return ResourceManager.GetString("Label_Invalid_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Contact.
        /// </summary>
        public static string Label_Key_Contact {
            get {
                return ResourceManager.GetString("Label_Key_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Label_Last_Name {
            get {
                return ResourceManager.GetString("Label_Last_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Label_ListItem_All {
            get {
                return ResourceManager.GetString("Label_ListItem_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All - Drug List.
        /// </summary>
        public static string Label_ListItem_Drug_All {
            get {
                return ResourceManager.GetString("Label_ListItem_Drug_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All States.
        /// </summary>
        public static string Label_ListItem_State_All {
            get {
                return ResourceManager.GetString("Label_ListItem_State_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Territories.
        /// </summary>
        public static string Label_ListItem_Territory_All {
            get {
                return ResourceManager.GetString("Label_ListItem_Territory_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All - Therapeutic Class.
        /// </summary>
        public static string Label_ListItem_Therapeutic_Class_All {
            get {
                return ResourceManager.GetString("Label_ListItem_Therapeutic_Class_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lives.
        /// </summary>
        public static string Label_Lives {
            get {
                return ResourceManager.GetString("Label_Lives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAC Jurisdiction.
        /// </summary>
        public static string Label_MAC_Jurisdictions {
            get {
                return ResourceManager.GetString("Label_MAC_Jurisdictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicaid Enrollment.
        /// </summary>
        public static string Label_Medicaid_Enrollment {
            get {
                return ResourceManager.GetString("Label_Medicaid_Enrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managed Medicaid Lives.
        /// </summary>
        public static string Label_Medicaid_Managed_Care_Enrollment {
            get {
                return ResourceManager.GetString("Label_Medicaid_Managed_Care_Enrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Policy Uploaded.
        /// </summary>
        public static string Label_Medical_Policy_Uploaded {
            get {
                return ResourceManager.GetString("Label_Medical_Policy_Uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Activity.
        /// </summary>
        public static string Label_Meeting_Activity {
            get {
                return ResourceManager.GetString("Label_Meeting_Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Type.
        /// </summary>
        public static string Label_Meeting_Type {
            get {
                return ResourceManager.GetString("Label_Meeting_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicaid Management Information Systems Fiscal Agent Services.
        /// </summary>
        public static string Label_MMISFAS {
            get {
                return ResourceManager.GetString("Label_MMISFAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Change Selection--.
        /// </summary>
        public static string Label_Multiple_Selection {
            get {
                return ResourceManager.GetString("Label_Multiple_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National.
        /// </summary>
        public static string Label_National {
            get {
                return ResourceManager.GetString("Label_National", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --No Selection--.
        /// </summary>
        public static string Label_No_Selection {
            get {
                return ResourceManager.GetString("Label_No_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Employees.
        /// </summary>
        public static string Label_Number_of_Employees {
            get {
                return ResourceManager.GetString("Label_Number_of_Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Name.
        /// </summary>
        public static string Label_Other_Name {
            get {
                return ResourceManager.GetString("Label_Other_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PA.
        /// </summary>
        public static string Label_PA {
            get {
                return ResourceManager.GetString("Label_PA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Name.
        /// </summary>
        public static string Label_ParentName {
            get {
                return ResourceManager.GetString("Label_ParentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy Benefit Managers.
        /// </summary>
        public static string Label_PBM {
            get {
                return ResourceManager.GetString("Label_PBM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services Offered.
        /// </summary>
        public static string Label_PBM_Service {
            get {
                return ResourceManager.GetString("Label_PBM_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage in Managed Care.
        /// </summary>
        public static string Label_Percentage_In_Managed_Care {
            get {
                return ResourceManager.GetString("Label_Percentage_In_Managed_Care", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy Lives.
        /// </summary>
        public static string Label_Pharmacy_Lives {
            get {
                return ResourceManager.GetString("Label_Pharmacy_Lives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Label_Phone {
            get {
                return ResourceManager.GetString("Label_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accreditation Status.
        /// </summary>
        public static string Label_Plan_AccreditationStatus {
            get {
                return ResourceManager.GetString("Label_Plan_AccreditationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classification.
        /// </summary>
        public static string Label_Plan_Classification {
            get {
                return ResourceManager.GetString("Label_Plan_Classification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Comments.
        /// </summary>
        public static string Label_Plan_Comments {
            get {
                return ResourceManager.GetString("Label_Plan_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Level.
        /// </summary>
        public static string Label_Plan_Level {
            get {
                return ResourceManager.GetString("Label_Plan_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Label_Plan_Name {
            get {
                return ResourceManager.GetString("Label_Plan_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Product.
        /// </summary>
        public static string Label_Plan_Product {
            get {
                return ResourceManager.GetString("Label_Plan_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Type.
        /// </summary>
        public static string Label_Plan_Type {
            get {
                return ResourceManager.GetString("Label_Plan_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Medicaid Preferred Drug List.
        /// </summary>
        public static string Label_Preferred_Drug_List {
            get {
                return ResourceManager.GetString("Label_Preferred_Drug_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Label_Product_Name {
            get {
                return ResourceManager.GetString("Label_Product_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product State Enrollment.
        /// </summary>
        public static string Label_Product_State_Enrollment {
            get {
                return ResourceManager.GetString("Label_Product_State_Enrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Type.
        /// </summary>
        public static string Label_Product_Type {
            get {
                return ResourceManager.GetString("Label_Product_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product National Enrollment.
        /// </summary>
        public static string Label_ProductNational_Enrollment {
            get {
                return ResourceManager.GetString("Label_ProductNational_Enrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products Discussed.
        /// </summary>
        public static string Label_Products_Discussed {
            get {
                return ResourceManager.GetString("Label_Products_Discussed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Home View.
        /// </summary>
        public static string Label_Quick_Home_View {
            get {
                return ResourceManager.GetString("Label_Quick_Home_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Filters.
        /// </summary>
        public static string Label_Report_Filters {
            get {
                return ResourceManager.GetString("Label_Report_Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Type.
        /// </summary>
        public static string Label_Report_Type {
            get {
                return ResourceManager.GetString("Label_Report_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restrictions.
        /// </summary>
        public static string Label_Restrictions {
            get {
                return ResourceManager.GetString("Label_Restrictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Label_Search {
            get {
                return ResourceManager.GetString("Label_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Filters.
        /// </summary>
        public static string Label_Search_Filters {
            get {
                return ResourceManager.GetString("Label_Search_Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information in this section was last updated on {0:d}.
        /// </summary>
        public static string Label_Section_Last_Updated {
            get {
                return ResourceManager.GetString("Label_Section_Last_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Type.
        /// </summary>
        public static string Label_Section_Name {
            get {
                return ResourceManager.GetString("Label_Section_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}.
        /// </summary>
        public static string Label_SellSheet_Step_Title {
            get {
                return ResourceManager.GetString("Label_SellSheet_Step_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string Label_Sign_Out {
            get {
                return ResourceManager.GetString("Label_Sign_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFS Lives.
        /// </summary>
        public static string Label_SM_FFS_Lives {
            get {
                return ResourceManager.GetString("Label_SM_FFS_Lives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Medicaid Health Care Management.
        /// </summary>
        public static string Label_SMHCM {
            get {
                return ResourceManager.GetString("Label_SMHCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Medical Pharmacy Benefit Administration.
        /// </summary>
        public static string Label_SMPBM {
            get {
                return ResourceManager.GetString("Label_SMPBM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialty Pharmacy Providers.
        /// </summary>
        public static string Label_SPP {
            get {
                return ResourceManager.GetString("Label_SPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string Label_State {
            get {
                return ResourceManager.GetString("Label_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to States Serviced.
        /// </summary>
        public static string Label_States_Serviced {
            get {
                return ResourceManager.GetString("Label_States_Serviced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Territory Name.
        /// </summary>
        public static string Label_Territory_Name {
            get {
                return ResourceManager.GetString("Label_Territory_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Territory #.
        /// </summary>
        public static string Label_Territory_No {
            get {
                return ResourceManager.GetString("Label_Territory_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Therapeutic Area.
        /// </summary>
        public static string Label_Therapeutic_Class {
            get {
                return ResourceManager.GetString("Label_Therapeutic_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tier.
        /// </summary>
        public static string Label_Tier {
            get {
                return ResourceManager.GetString("Label_Tier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All &lt;span style=&apos;font-weight:bold&apos;&gt;{0}&lt;/span&gt; Accounts having &lt;span style=&apos;font-weight:bold&apos;&gt;{1}&lt;/span&gt; on Tier Status: &lt;span style=&apos;font-weight:bold&apos;&gt;{2}&lt;/span&gt;.
        /// </summary>
        public static string Label_Tier_Coverage_DrillDown {
            get {
                return ResourceManager.GetString("Label_Tier_Coverage_DrillDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tier Coverage.
        /// </summary>
        public static string Label_TierCoverage {
            get {
                return ResourceManager.GetString("Label_TierCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy Lives\n(Millions).
        /// </summary>
        public static string Label_TierCoverage_PharmacyLives {
            get {
                return ResourceManager.GetString("Label_TierCoverage_PharmacyLives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Label_TierOption {
            get {
                return ResourceManager.GetString("Label_TierOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Label_Title {
            get {
                return ResourceManager.GetString("Label_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Covered Lives.
        /// </summary>
        public static string Label_Total_Covered_Lives {
            get {
                return ResourceManager.GetString("Label_Total_Covered_Lives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total State Medicare Part D Enrollment.
        /// </summary>
        public static string Label_Total_MedD_State_Enrollment {
            get {
                return ResourceManager.GetString("Label_Total_MedD_State_Enrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Pharmacy Lives.
        /// </summary>
        public static string Label_Total_Pharmacy_Lives {
            get {
                return ResourceManager.GetString("Label_Total_Pharmacy_Lives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a document name..
        /// </summary>
        public static string Label_Upload_Document_Name_Validator {
            get {
                return ResourceManager.GetString("Label_Upload_Document_Name_Validator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Favorites.
        /// </summary>
        public static string Label_View_Favorites {
            get {
                return ResourceManager.GetString("Label_View_Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VISN.
        /// </summary>
        public static string Label_VISN {
            get {
                return ResourceManager.GetString("Label_VISN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Label_Website {
            get {
                return ResourceManager.GetString("Label_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP.
        /// </summary>
        public static string Label_ZIP {
            get {
                return ResourceManager.GetString("Label_ZIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a document to delete..
        /// </summary>
        public static string Message_CCR_Delete_Document {
            get {
                return ResourceManager.GetString("Message_CCR_Delete_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a plan..
        /// </summary>
        public static string Message_CCR_Select_Plan {
            get {
                return ResourceManager.GetString("Message_CCR_Select_Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter No. of Sell Sheets properly..
        /// </summary>
        public static string Message_Correct_NoSellSheets {
            get {
                return ResourceManager.GetString("Message_Correct_NoSellSheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Failed: Please contact Pinsonault support with error code {0}.
        /// </summary>
        public static string Message_DataService_Request_Failed {
            get {
                return ResourceManager.GetString("Message_DataService_Request_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Service request failed because the host of the Referring URL does not match the data service&apos;s host name..
        /// </summary>
        public static string Message_DataService_Request_Failed_InvalidHost {
            get {
                return ResourceManager.GetString("Message_DataService_Request_Failed_InvalidHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Service request failed because the User-Agent and/or Referring URL could not be verified..
        /// </summary>
        public static string Message_DataService_Request_Failed_NotBrowser {
            get {
                return ResourceManager.GetString("Message_DataService_Request_Failed_NotBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a reminder that: (i) the PathfinderRx data that you have downloaded is the property of Pinsonault Associates; and that (ii) pursuant to a contract between Pinsonault Associates and {0}, you may not disclose this data, in whole or in part, to any third party..
        /// </summary>
        public static string Message_Export_Confirmation {
            get {
                return ResourceManager.GetString("Message_Export_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to access Favorites..
        /// </summary>
        public static string Message_Favorites_Permission {
            get {
                return ResourceManager.GetString("Message_Favorites_Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;drillDownInstruct&quot;&gt;(Click part of the grid or bar chart to view drill down details)&lt;/div&gt;.
        /// </summary>
        public static string Message_Formulary_Status_DrillDown {
            get {
                return ResourceManager.GetString("Message_Formulary_Status_DrillDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All previous steps must be completed prior to selecting this step. The next step to complete is &quot;{0}&quot;..
        /// </summary>
        public static string Message_FormularySellSheets_Step_Error {
            get {
                return ResourceManager.GetString("Message_FormularySellSheets_Step_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Message_Loading {
            get {
                return ResourceManager.GetString("Message_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no addresses available for this account..
        /// </summary>
        public static string Message_No_Addresses {
            get {
                return ResourceManager.GetString("Message_No_Addresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have any saved favorites..
        /// </summary>
        public static string Message_No_Favorites_Added {
            get {
                return ResourceManager.GetString("Message_No_Favorites_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no records to display..
        /// </summary>
        public static string Message_No_Records {
            get {
                return ResourceManager.GetString("Message_No_Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;bull;&amp;nbsp;Addr1 is required..
        /// </summary>
        public static string Message_Required_Addr1 {
            get {
                return ResourceManager.GetString("Message_Required_Addr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;bull;&amp;nbsp;Designation is Required.
        /// </summary>
        public static string Message_Required_Designation {
            get {
                return ResourceManager.GetString("Message_Required_Designation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one drug..
        /// </summary>
        public static string Message_Required_DrugSelection {
            get {
                return ResourceManager.GetString("Message_Required_DrugSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;bull;&amp;nbsp;First Name is Required.
        /// </summary>
        public static string Message_Required_FirstName {
            get {
                return ResourceManager.GetString("Message_Required_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;bull;&amp;nbsp;Last Name is Required.
        /// </summary>
        public static string Message_Required_LastName {
            get {
                return ResourceManager.GetString("Message_Required_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;bull;&amp;nbsp;No. of Sell Sheets field is required..
        /// </summary>
        public static string Message_Required_NoSellSheets {
            get {
                return ResourceManager.GetString("Message_Required_NoSellSheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;bull;&amp;nbsp;Printer Email is required..
        /// </summary>
        public static string Message_Required_PrinterEmail {
            get {
                return ResourceManager.GetString("Message_Required_PrinterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one product..
        /// </summary>
        public static string Message_Required_ProductSelection {
            get {
                return ResourceManager.GetString("Message_Required_ProductSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;bull;&amp;nbsp;Ship Location is required..
        /// </summary>
        public static string Message_Required_ShipLocation {
            get {
                return ResourceManager.GetString("Message_Required_ShipLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;drillDownInstruct&quot;&gt;(Click part of the grid or bar chart to view drill down details)&lt;/div&gt;.
        /// </summary>
        public static string Message_Tier_Coverage_DrillDown {
            get {
                return ResourceManager.GetString("Message_Tier_Coverage_DrillDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying user name and password....
        /// </summary>
        public static string Message_VerifyingUser {
            get {
                return ResourceManager.GetString("Message_VerifyingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a website.
        /// </summary>
        public static string PopupTitle_Website_Selection {
            get {
                return ResourceManager.GetString("PopupTitle_Website_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [a-z0-9!#$%&amp;&apos;*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&amp;&apos;*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?.
        /// </summary>
        public static string RegularExpression_Email {
            get {
                return ResourceManager.GetString("RegularExpression_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affiliation Formulary Report.
        /// </summary>
        public static string SectionTitle_AffiliationFormularyReport {
            get {
                return ResourceManager.GetString("SectionTitle_AffiliationFormularyReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benefit Design.
        /// </summary>
        public static string SectionTitle_BenefitDesign {
            get {
                return ResourceManager.GetString("SectionTitle_BenefitDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benefit Design - Drug Level.
        /// </summary>
        public static string SectionTitle_BenefitDesign_DrugLevel {
            get {
                return ResourceManager.GetString("SectionTitle_BenefitDesign_DrugLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Planning.
        /// </summary>
        public static string SectionTitle_BusinessPlanning {
            get {
                return ResourceManager.GetString("SectionTitle_BusinessPlanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Plans Report.
        /// </summary>
        public static string SectionTitle_BusinessPlanReport {
            get {
                return ResourceManager.GetString("SectionTitle_BusinessPlanReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Plans.
        /// </summary>
        public static string SectionTitle_ChildPlan {
            get {
                return ResourceManager.GetString("SectionTitle_ChildPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Covered Lives.
        /// </summary>
        public static string SectionTitle_CoveredLives {
            get {
                return ResourceManager.GetString("SectionTitle_CoveredLives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulary Status.
        /// </summary>
        public static string SectionTitle_FormularyCoverage {
            get {
                return ResourceManager.GetString("SectionTitle_FormularyCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulary Restrictions.
        /// </summary>
        public static string SectionTitle_FormularyStatus {
            get {
                return ResourceManager.GetString("SectionTitle_FormularyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical Formulary.
        /// </summary>
        public static string SectionTitle_HxReport {
            get {
                return ResourceManager.GetString("SectionTitle_HxReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Contacts.
        /// </summary>
        public static string SectionTitle_KeyContacts {
            get {
                return ResourceManager.GetString("SectionTitle_KeyContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lives Distribution Report.
        /// </summary>
        public static string SectionTitle_LivesDistributionReport {
            get {
                return ResourceManager.GetString("SectionTitle_LivesDistributionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Key Contacts.
        /// </summary>
        public static string SectionTitle_MyKeyContacts {
            get {
                return ResourceManager.GetString("SectionTitle_MyKeyContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Plan.
        /// </summary>
        public static string SectionTitle_ParentPlan {
            get {
                return ResourceManager.GetString("SectionTitle_ParentPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affiliations.
        /// </summary>
        public static string SectionTitle_PlanAffiliations {
            get {
                return ResourceManager.GetString("SectionTitle_PlanAffiliations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Information.
        /// </summary>
        public static string SectionTitle_PlanInfo {
            get {
                return ResourceManager.GetString("SectionTitle_PlanInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string SectionTitle_PlanInfoAddress {
            get {
                return ResourceManager.GetString("SectionTitle_PlanInfoAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Information.
        /// </summary>
        public static string SectionTitle_ProdInfo {
            get {
                return ResourceManager.GetString("SectionTitle_ProdInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulary Sell Sheets.
        /// </summary>
        public static string SectionTitle_SellSheets {
            get {
                return ResourceManager.GetString("SectionTitle_SellSheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services Offered.
        /// </summary>
        public static string SectionTitle_ServicesOffered {
            get {
                return ResourceManager.GetString("SectionTitle_ServicesOffered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tier Coverage.
        /// </summary>
        public static string SectionTitle_TierCoverage {
            get {
                return ResourceManager.GetString("SectionTitle_TierCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PathfinderRx: {0} - {1} Key Contact.
        /// </summary>
        public static string Subject_Submit_Key_Contact_Update {
            get {
                return ResourceManager.GetString("Subject_Submit_Key_Contact_Update", resourceCulture);
            }
        }
    }
}
